apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
                port: 80
              initialDelaySeconds: 30
              periodSeconds: 30
          readinessProb:
            httpGet:
              path: /
                port: 80
              initialDelaySeconds: 15
              periodSeconds: 3
